# Generated by Django 4.1.4 on 2022-12-12 12:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0001_initial'),
        ('connexion', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='contributeurs',
            field=models.ManyToManyField(related_name='contributions', through='connexion.Contributeur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='probleme',
            name='assigne',
            field=models.ForeignKey(on_delete=models.SET(models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auteur', to=settings.AUTH_USER_MODEL)), related_name='assigne', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='probleme',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auteur', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='probleme',
            name='projet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.projet'),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='auteur',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='commentaire',
            name='probleme',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.probleme'),
        ),
    ]
