# Generated by Django 4.1.4 on 2022-12-12 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='accessible',
            field=models.BooleanField(default=False),
        ),
    ]
